version: 2
updates:
  # GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'ci'
    groups:
      all:
        patterns:
          - '*'
      security:
        applies-to: security-updates
        patterns:
          - '*'

  # npm
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'deps'
    groups:
      all:
        patterns:
          - '*'
      security:
        applies-to: security-updates
        patterns:
          - '*'
